// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onBlindsAngleChange();

CloudDimmedLight blinds_angle;

void initProperties(){

  ArduinoCloud.addProperty(blinds_angle, READWRITE, ON_CHANGE, onBlindsAngleChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
